name: Fly Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy website to Fly
    runs-on: codeberg-small-lazy
    concurrency: deploy-group
    steps:
      - name: Checkout repository
        uses: https://code.forgejo.org/actions/checkout@v4
    
      - name: Run flyctl
        uses: https://github.com/superfly/flyctl-actions/setup-flyctl@master
        with:
          version: v0.3.178
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

